# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f32b9ee437b551569e0f5d08e830ae0fdb9a9ecbe463aa861f718cc40d136f50a84a28309ff76758347b40b5f9b5e5307613fe28efdd92ce97c16a741121bb3a

test:
  secret_key_base: 8c5299dd85a19ca0b4b977c89158009ce70d4fb1c49bc8f75ae6cdf25ceb1a78fe87676fdcbea98a4a863e69083a6bc20ad04078e58e0ad216a4f3e8db0f96f9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
